# Generated by Django 6.1.1 on 2026-10-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_processoroperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='failure_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
