# Generated by Django 6.1.1 on 2026-10-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paymentjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentjob',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentjob',
            name='processor_operation_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
